name = "ScalarRadau"
uuid = "52145ff8-3717-48bc-b8ab-44d3704098ee"
authors = ["Mark Baum <markmbaum@protonmail.com>"]
version = "1.0.5"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
StaticArrays = "1.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
